name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Run build
      run: ./gradlew build
    - name: Archive test reports
      id: archive-logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        retention-days: 7
        path: |
          app/build/reports/tests/
          nvd-lib/build/reports/tests/
