name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Run build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ./gradlew build --info
    - name: Archive test reports
      id: archive-logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        retention-days: 7
        path: |
          vulnz/build/reports/tests
          open-vulnerability-clients/build/reports/tests
