name: docker pr

on:
  push:
    tags:
      - v*

env:
  GHCR_IMAGE_FQDN: ghcr.io/jeremylong/open-vulnerability-data-mirror
  HUB_IMAGE_FQDN: jeremylong/open-vulnerability-data-mirror
  VERSION: ${{ github.ref_name }}

jobs:
  docker-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Run build
        run: ./gradlew -x test -Pversion=${{ env.VERSION }} vulnz:build
      - name: Build docker image
        uses: docker/build-push-action@v6
        with:
          context: vulnz/
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.GHCR_IMAGE_FQDN }}:${{ env.VERSION }}
            ${{ env.GHCR_IMAGE_FQDN }}:latest
            ${{ env.HUB_IMAGE_FQDN }}:${{ env.VERSION }}
            ${{ env.HUB_IMAGE_FQDN }}:latest
          build-args: |
            BUILD_VERSION=${{ env.VERSION }}
