name: docker pr

on:
  push:
    tags:
      - vulnz/*

env:
  IMAGE_FQDN: ghcr.io/jeremylong/vulnz
  VERSION: ${{ github.ref_name }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew -x test -Pversion=${{ env.VERSION }} vulnz:build
      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          context: vulnz/
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE_FQDN }}:${{ env.VERSION }}
          build-args: |
            BUILD_VERSION=${{ env.VERSION }}
