name: docker pr

on:
  push:
    branches-ignore:
      - 'main'

env:
  IMAGE_FQDN: ghcr.io/jeremylong/vulnz
  #VERSION: 0.0.0-SNAPSHOT
  VERSION: 5.1.1

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Run build
        run: ./gradlew -x test -Pversion=${{ env.VERSION }} vulnz:build
      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          context: vulnz/
          platforms: linux/amd64
          push: false
          tags: |
            ${{ env.IMAGE_FQDN }}:${{ env.VERSION }}
          build-args: |
            BUILD_VERSION=${{ env.VERSION }}
